9apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubegateway
  name: kubegateway
spec:
  ports:
  - port: 9002
    protocol: TCP
    targetPort: 9002
  selector:
    app: kubegateway
  type: NodePort
status:
  loadBalancer: {}
